language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - 10

script:
  - npm run build

deploy:
  cleanup: false
  keep_history: true
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master

env:
  global:
  - secure: "dNDE0CiMRJ0sBCSYgkO5EU+dVTLAuazriwYapkLDlQGiBNp7I4Q/eROXQJHu6eXfUok9qw9G9bxgZTzOqBek2uS1Iy4WU5O3dYSVM8OsMZeBq89WVAm1ML1dZC+EVbI35OWY4L3rBzQnWu5NLGEWIikndcUqQ54IZo6amxNVwfxANaLgIg/KOJr++eqVnkkGSFlpAB//6VoVCPdM51/O3qM0aHym6mu7PJl+uPGMSWD+x5IoOvtnxojntLj0CnQWdR+SgTeoJVD8C3sbLogh9X/T9VsLMOR6TGtfgH3Rpa80n79NodZQMFwhl33iXHnuMs6IhuD+VTi5K9pyx2BOXVQxZK6OzGxDP5ax0Hy02F0mjnk6CHUG9N6CWeuD6NRXKThCxxdxcVSP3XK35uw9kosokkZQjtpWZfNnZBy3KrKTV4vIoRX72nXttpHqs7GHbz/bcHlahCI2ssHOENI5QqKXqZom8VfMT5xA6HIyWczH/2DSMeUNcBm3uU/8GVE5OHIoelKRwDmIYrjHz862Y298OawgV9QtpoE2IQT6UgGi3Uyr0ntJTHXWi6LxA2IyoB+WRh1rZ7k+L7najb5XKWt3CtBscqOcneZ2RraFc2HDPNt9iC5rIL+5lfxZRKY/wWe0dnYLzVUUo8nFz3wTu39VZsxq3kg8UJsOGIAwkgk="
